name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        packer_version:
          - '1.8'
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: andych
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU for multi-platform Docker build
      uses: docker/setup-qemu-action@v2
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: andych/packer-ansible:${{ matrix.packer_version }}
        build-args: |
          packer_version=${{ matrix.packer_version }}
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm64
